version: '3'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27018:27017
    restart: always
    volumes:
      - /data/db
  backend:
    command: bash -c "npm install && npm run dev"
    depends_on:
      - mongo
    env_file: .env
    image: node:carbon
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
